spring:
  application:
    name: springboottest
  redis:
    host: localhost
    port: 6379
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o-mini

server:
  port: 8080

naver:
  client:
    id: ${NAVER_ID}
    secret: ${NAVER_SECRET}

kakao:
  api:
    key: ${KAKAO_KEY}