spring:
  application:
    name: springboottest
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o-mini

mybatis:
  type-aliases-package: com.example.springboottest.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

naver:
  client:
    id: ${NAVER_ID}
    secret: ${NAVER_SECRET}

kakao:
  api:
    key: ${KAKAO_KEY}

skopenapi:
  api:
    key: ${SK_KEY}